"""initial schema

Revision ID: 164e2b863589
Revises: 
Create Date: 2026-09-09 21:00:54.347962

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '164e2b863589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('key_id', sa.String(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.Enum('free', 'self_serve', 'licensing', name='plan_tier'), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('domains',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_json_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('agent_json_s3_key', sa.String(), nullable=True),
    sa.Column('llms_txt_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('llms_txt_s3_key', sa.String(), nullable=True),
    sa.Column('web_bot_auth_present', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('web_bot_auth_key_id', sa.String(), nullable=True),
    sa.Column('web_bot_auth_valid', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('web_bot_auth_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declared_capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('confidence_flags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('on_chain_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('monitors',
    sa.Column('monitor_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('webhook_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain'], ['domains.domain'], ),
    sa.PrimaryKeyConstraint('monitor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitors')
    op.drop_table('domains')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
