"""manifest and web bot auth malformed reasons

Revision ID: 7614f244937d
Revises: 05c793fc3af7
Create Date: 2026-09-12 16:42:52.068485

A real user asked for this after testing the public lookup page: a
"couldn't be parsed" result told them THAT agents.json or the Web Bot
Auth directory was malformed but never WHY, which is the one thing a
site owner actually debugging their own setup needs. `confidence_flags`
has no room for free text (just short flag strings), so this adds two
nullable columns for a short, specific, human-readable diagnostic --
`manifest_malformed_reason` (set alongside `malformed_manifest`) and
`web_bot_auth_malformed_reason` (set alongside `malformed_web_bot_auth`),
`None` otherwise. See `parser/manifest.py`/`parser/webbotauth.py` for
where these are produced.

Both columns are nullable with no backfill: existing malformed rows
(all from this build's own local/LocalStack testing, never a real
production deployment -- no `terraform apply` has ever run) simply
read back `NULL` for a reason until the next recrawl repopulates it,
same precedent as every prior migration in this schema.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7614f244937d'
down_revision: Union[str, None] = '05c793fc3af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('manifest_malformed_reason', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('web_bot_auth_malformed_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'web_bot_auth_malformed_reason')
    op.drop_column('domains', 'manifest_malformed_reason')
    # ### end Alembic commands ###
